class _BotCommands:
    def __init__(self):
        self.Start2Command = 'start'
        self.Mirror2Command = 'mirror'
        self.UnzipMirror2Command = 'unzipmirror'
        self.TarMirror2Command = 'tarmirror'
        self.CancelMirror2 = 'cancel'
        self.CancelAll2Command = 'cancelall'
        self.List2Command = 'list'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.Restart2Command = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.Clone2Command = 'clone'
        self.Count2Command = 'count'
        self.Watch2Command = 'watch'
        self.TarWatch2Command = 'tarwatch'
        self.Delete2Command = 'del'
        self.UsageCommand = 'usage'
        self.MediaInfoCommand = 'mediainfo'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'

BotCommands = _BotCommands()
